version: '3'
services:
  application:
    container_name: app
    build:
      context: .
      target: development
    command: npm run start:dev
    # env_file:
    #   - .env
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - network
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:alpine
    container_name: postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network
    ports:
      - 5432:5432
    restart: always

networks:
  network:
volumes:
  postgres-data:
